export const sabado = [
  { banca: "A", n: 1, nombre: "Agustina Ignacia Garrido Miranda", club: "HUELLAS", categoria: "MINI F ML" },
  { banca: "B", n: 1, nombre: "Victoria Wilde Garrido", club: "CISNES", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 2, nombre: "Agustina Pia Schafer Banados", club: "PAILLACO", categoria: "MINI F ML" },
  { banca: "B", n: 2, nombre: "Valentina Rebolledo", club: "ALMA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 3, nombre: "Alba Simone Vives Hidalgo", club: "PAILLACO", categoria: "MINI F ML" },
  { banca: "B", n: 3, nombre: "Valentina Isabella Carrillo Henriquez", club: "AMARANTA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 4, nombre: "Alondra Valentina Acevedo Gatica", club: "FUTRONO", categoria: "MINI F ML" },
  { banca: "B", n: 4, nombre: "Stephanie Nicole Monroy Maldonado", club: "AMULEN", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 5, nombre: "Amanda Aguilera", club: "GREENHOUSE", categoria: "MINI F ML" },
  { banca: "B", n: 5, nombre: "Sophia Vollmer Tenorio", club: "TALENTOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 6, nombre: "Amanda Ysabel Godoy Briceno", club: "ELITE", categoria: "MINI F ML" },
  { banca: "B", n: 6, nombre: "Sophia Gomez Mellado", club: "TALENTOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 7, nombre: "Amira Leticia Velazco Acosta", club: "ORIGENES", categoria: "MINI F ML" },
  { banca: "B", n: 7, nombre: "Sofia Nercelles", club: "PAILLACO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 8, nombre: "Antonella Giacomozzi Vera", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 8, nombre: "Sofia Munoz Toledo", club: "CAH", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 9, nombre: "Antonia Fonseca Vera", club: "CHAYTOR", categoria: "MINI F ML" },
  { banca: "B", n: 9, nombre: "Sofia Antonella Gonzalez Perez", club: "PAILLACO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 10, nombre: "Arantza Yuliet Yumar Lobo", club: "ELITE", categoria: "MINI F ML" },
  { banca: "B", n: 10, nombre: "Renata Isidora Cobos Ili", club: "PAILLACO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 11, nombre: "Barbara Zuniga Mancilla", club: "TRAVESIA", categoria: "MINI F ML" },
  { banca: "B", n: 11, nombre: "Pia Torres Zamorano", club: "CHAYTOR", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 12, nombre: "Begona Arrigorriaga Pinto", club: "CHAYTOR", categoria: "MINI F ML" },
  { banca: "B", n: 12, nombre: "Monserrat Contreras Tejos", club: "GR LAUTARO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 13, nombre: "Carlota Daniella Gutierrez Camargo", club: "ELITE", categoria: "MINI F ML" },
  { banca: "B", n: 13, nombre: "Matilde De Jourdan Carrillo", club: "ALEMAN VILLARRICA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 14, nombre: "Colomba Thomas Leiva", club: "FRESIA", categoria: "MINI F ML" },
  { banca: "B", n: 14, nombre: "Matilda Nett Navarrete", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 15, nombre: "Ema Alejandra Quiyinao Barrientos", club: "ORIGENES", categoria: "MINI F ML" },
  { banca: "B", n: 15, nombre: "Matilda Dumenes Rojas", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 16, nombre: "Emilia Antonela Carcamo Quezada", club: "PAILLACO", categoria: "MINI F ML" },
  { banca: "B", n: 16, nombre: "Martina Miralles", club: "GR VALDIVIA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 17, nombre: "Emilia Navarrete Tillemann", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 17, nombre: "Maithe Aguilar Rodriguez", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 18, nombre: "Emma Catalina Baeza Aguilera", club: "ORIGENES", categoria: "MINI F ML" },
  { banca: "B", n: 18, nombre: "Maite Nunez Fernandez", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 19, nombre: "Emma Victoria Luengo Chacon", club: "R.ESPANOLA", categoria: "MINI F ML" },
  { banca: "B", n: 19, nombre: "Magdalena Calisto Cisterna", club: "TRAVESIA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 20, nombre: "Florencia Isidora Millar Navarrete", club: "AMULEN", categoria: "MINI F ML" },
  { banca: "B", n: 20, nombre: "Laura Paz Hernandez Saez", club: "HUELLAS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 21, nombre: "Gretta Gonzalez Pineda", club: "PAILLACO", categoria: "MINI F ML" },
  { banca: "B", n: 21, nombre: "Laura Duran Werth", club: "ALEMAN VILLARRICA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 22, nombre: "Helena Yanez Munoz", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 22, nombre: "Josefina Vasquez Sayeg", club: "TALENTOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 23, nombre: "Ignacia Araya", club: "GR VALDIVIA", categoria: "MINI F ML" },
  { banca: "B", n: 23, nombre: "Josefina Pauline Schafer Banados", club: "PAILLACO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 24, nombre: "Ignacia Barrientos Rubio", club: "FRESIA", categoria: "MINI F ML" },
  { banca: "B", n: 24, nombre: "Josefa Verdello", club: "GREENHOUSE", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 25, nombre: "Ignacia Pedrero Herrera", club: "TALENTOS", categoria: "MINI F ML" },
  { banca: "B", n: 25, nombre: "Josefa Admore Jaduri Cardenas", club: "PAILLACO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 26, nombre: "Isidora Farina Cardenas", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 26, nombre: "Javiera Saavedra Santos", club: "TALENTOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 27, nombre: "Isidora Medina Andrades", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 27, nombre: "Isidora Jimenez", club: "GREENHOUSE", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 28, nombre: "Isis Elisa Yanez Poveda", club: "CAH", categoria: "MINI F ML" },
  { banca: "B", n: 28, nombre: "Isidora Cespedez", club: "GREENHOUSE", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 29, nombre: "Jacinta Larrain Painemal", club: "CHAYTOR", categoria: "MINI F ML" },
  { banca: "B", n: 29, nombre: "Isabella Alexandra Lagos Carrasco", club: "R.ESPANOLA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 30, nombre: "Joaquina Masias Duarte", club: "TALENTOS", categoria: "MINI F ML" },
  { banca: "B", n: 30, nombre: "Genesis Hernandez Martinez", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 31, nombre: "Julieta Silva Rojas", club: "GR LAUTARO", categoria: "MINI F ML" },
  { banca: "B", n: 31, nombre: "Florencia Villa", club: "GREENHOUSE", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 32, nombre: "Leonor Diaz Shaefer", club: "FRESIA", categoria: "MINI F ML" },
  { banca: "B", n: 32, nombre: "Florencia Jaramillo Echeverria", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 33, nombre: "Leonor Gutierrez Abarzua", club: "CHAYTOR", categoria: "MINI F ML" },
  { banca: "B", n: 33, nombre: "Florencia Gallardo", club: "GR VALDIVIA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 34, nombre: "Maria Gracia Silva Vergara", club: "ALEMAN VILLARRICA", categoria: "MINI F ML" },
  { banca: "B", n: 34, nombre: "Fernanda Carolina Navarrete Rademacher", club: "HUELLAS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 35, nombre: "Maria Victoria Cortes", club: "AMARANTA", categoria: "MINI F ML" },
  { banca: "B", n: 35, nombre: "Fernanda Avila Carrasco", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 36, nombre: "Pia Garces Pizarro", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 36, nombre: "Emily Ayelen Espinoza Garces", club: "AMULEN", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 37, nombre: "Rocio Tapia Castaneda", club: "TALENTOS", categoria: "MINI F ML" },
  { banca: "B", n: 37, nombre: "Emilia Obando", club: "GR VALDIVIA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 38, nombre: "Sharlot Gimena Caldera Alvarez", club: "OLYMPUS", categoria: "MINI F ML" },
  { banca: "B", n: 38, nombre: "Emilia Antonia Tejo Montes", club: "PAILLACO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 39, nombre: "Sofia Carrasco Silva", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 39, nombre: "Belen Medina Pizarro", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 40, nombre: "Trinidad Montenegro", club: "GR VALDIVIA", categoria: "MINI F ML" },
  { banca: "B", n: 40, nombre: "Asuncion Teuber", club: "GERMANIA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 41, nombre: "Trinidad Sagredo Silva", club: "TRAVESIA", categoria: "MINI F ML" },
  { banca: "B", n: 41, nombre: "Antonia Sandoval Alvarado", club: "TALENTOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 42, nombre: "Valentina Patricia Cardenas Verdugo", club: "AMULEN", categoria: "MINI F ML" },
  { banca: "B", n: 42, nombre: "Antonia Osorio Millalen", club: "GR LAUTARO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 43, nombre: "Valentina Rafaela Lopez Tejeda", club: "OLYMPUS", categoria: "MINI F ML" },
  { banca: "B", n: 43, nombre: "Antonia Hevia Diaz", club: "CHAYTOR", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 44, nombre: "Violeta Hernandez Vergara", club: "GR LAUTARO", categoria: "MINI F ML" },
  { banca: "B", n: 44, nombre: "Antonia Gatica Mendez", club: "ALEMAN VILLARRICA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 45, nombre: "Valentina Gonzalez Flores", club: "ALMA", categoria: "TC F ML" },
  { banca: "B", n: 45, nombre: "Antonella Delgado Barria", club: "TRAVESIA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 46, nombre: "Valentina Alejandra Cotal Villanueva", club: "PAILLACO", categoria: "TC F ML" },
  { banca: "B", n: 46, nombre: "Antonella Cofre Conoman", club: "AMULEN", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 47, nombre: "Sofia Alvarez Alve", club: "ALMA", categoria: "TC F ML" },
  { banca: "B", n: 47, nombre: "Amanda Sumps Socias", club: "ALEMAN VILLARRICA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 48, nombre: "Rebeca Schwerter Thiers", club: "ALEMAN TEMUCO", categoria: "TC F ML" },
  { banca: "B", n: 48, nombre: "Amanda Cayulef", club: "CAH", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 49, nombre: "Mila Ignacia Tilleria Ponce", club: "ORIGENES", categoria: "TC F ML" },
  { banca: "B", n: 49, nombre: "Agustina Romero", club: "CAH", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 50, nombre: "Maria Javiera Negroni", club: "ALMA", categoria: "TC F ML" },
  { banca: "B", n: 50, nombre: "Agustina Lagos", club: "GREENHOUSE", categoria: "PEQUE F ML" },
  { banca: "A", n: 51, nombre: "Josefa Vidal Cid", club: "GR LAUTARO", categoria: "TC F ML" },
  { banca: "B", n: 51, nombre: "Antonia Martina Garcia Navarro", club: "AMARANTA", categoria: "PEQUE F ML" },
  { banca: "A", n: 52, nombre: "Josefa Trinidad Sepulveda Lobos", club: "AMARANTA", categoria: "TC F ML" },
  { banca: "B", n: 52, nombre: "Aurora Sofia Fischer Michaelis", club: "AMARANTA", categoria: "PEQUE F ML" },
  { banca: "A", n: 53, nombre: "Josefa Leonor Ormazabal Andrade", club: "ELITE", categoria: "TC F ML" },
  { banca: "B", n: 53, nombre: "Blanca Stubing Neumann", club: "ALEMAN TEMUCO", categoria: "PEQUE F ML" },
  { banca: "A", n: 54, nombre: "Florencia Vergara", club: "GR VALDIVIA", categoria: "TC F ML" },
  { banca: "B", n: 54, nombre: "Carolina Torres Zamorano", club: "CHAYTOR", categoria: "PEQUE F ML" },
  { banca: "A", n: 55, nombre: "Fernanda Reyes", club: "GR VALDIVIA", categoria: "TC F ML" },
  { banca: "B", n: 55, nombre: "Emma Ignacia Mayorga Gomez", club: "AMARANTA", categoria: "PEQUE F ML" },
  { banca: "A", n: 56, nombre: "Antonia Munoz", club: "GR VALDIVIA", categoria: "TC F ML" },
  { banca: "B", n: 56, nombre: "Esmeralda Casanueva Ibanez", club: "AMARANTA", categoria: "PEQUE F ML" },
  { banca: "A", n: 57, nombre: "Antonia Catalina Solis Gonzalez", club: "ARA", categoria: "TC F ML" },
  { banca: "B", n: 57, nombre: "Isabella Barriga", club: "NOVA STELLA", categoria: "PEQUE F ML" },
  { banca: "A", n: 58, nombre: "Antonella Dominga Vergara Ruiz", club: "R.ESPANOLA", categoria: "TC F ML" },
  { banca: "B", n: 58, nombre: "Isidora Bollman Jaramillo", club: "GR LAUTARO", categoria: "PEQUE F ML" },
  { banca: "A", n: 59, nombre: "Amanda Gomez", club: "CAH", categoria: "TC F ML" },
  { banca: "B", n: 59, nombre: "Isidora Caamano Gutierrez", club: "ALEMAN TEMUCO", categoria: "PEQUE F ML" },
  { banca: "A", n: 60, nombre: "Agustina Monserrat Salinas Urrutia", club: "R.ESPANOLA", categoria: "TC F ML" },
  { banca: "B", n: 60, nombre: "Isidora Teuber Gonzalez", club: "ALEMAN TEMUCO", categoria: "PEQUE F ML" },
  { banca: "A", n: 61, nombre: "Ambar Astroza", club: "OHIGGINS", categoria: "PEQUE C ML" },
  { banca: "B", n: 61, nombre: "Josefa Larrain Painemal", club: "CHAYTOR", categoria: "PEQUE F ML" },
  { banca: "A", n: 62, nombre: "Magdalena Oyarzo Beltran", club: "OHIGGINS", categoria: "PEQUE C ML" },
  { banca: "B", n: 62, nombre: "Marianna Pena Sepulveda", club: "CISNES", categoria: "PEQUE F ML" },
  { banca: "A", n: 63, nombre: "Maite Vargas Lerchundi", club: "ALMA", categoria: "PEQUE C ML" },
  { banca: "B", n: 63, nombre: "Matilde Antonia Rivera Figueroa", club: "AMARANTA", categoria: "PEQUE F ML" },
  { banca: "A", n: 64, nombre: "Sofia Valenzuela", club: "OHIGGINS", categoria: "PEQUE C ML" },
  { banca: "B", n: 64, nombre: "Mia Hoffmann Canete", club: "R.ESPANOLA", categoria: "PEQUE F ML" }
];

export const domingo = [
  { banca: "A", n: 1, nombre: "Agustina Ormazabal", club: "CAH", categoria: "INFANTIL F ML" },
  { banca: "B", n: 1, nombre: "Agustina Chavez Henriquez", club: "OHIGGINS", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 2, nombre: "Agustina Vargas Vara", club: "ALMA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 2, nombre: "Alfonsina Higuera Aburto", club: "ORIGENES", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 3, nombre: "Amelie Schadt Brunner", club: "ALEMAN VILLARRICA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 3, nombre: "Alonsa Ignacia Sandoval Salas", club: "ELITE", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 4, nombre: "Blanca Reinike Duran", club: "ALEMAN VILLARRICA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 4, nombre: "Antonia Florencia Ruiz Bravo", club: "AMARANTA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 5, nombre: "Emilia Antonia Azua Letelier", club: "ARA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 5, nombre: "Antonia Sepulveda", club: "CAH", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 6, nombre: "Emilia Diaz Miranda", club: "TRAVESIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 6, nombre: "Fernanda Javiera Dominguez Manquel", club: "OLYMPUS", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 7, nombre: "Emilia Mora Gaete", club: "TALENTOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 7, nombre: "Javiera Anais Valencia Vallejo", club: "AMARANTA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 8, nombre: "Emily Garate", club: "GR VALDIVIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 8, nombre: "Josefina Ignacia Morales Valenzuela", club: "AMARANTA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 9, nombre: "Emma Schneider Trejo", club: "ALEMAN TEMUCO", categoria: "INFANTIL F ML" },
  { banca: "B", n: 9, nombre: "Laura Barckhahn", club: "NOVA STELLA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 10, nombre: "Emma Yurjevic Moreno", club: "ALEMAN VILLARRICA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 10, nombre: "Llampuzken Raimil", club: "KUYEN", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 11, nombre: "Evelyn Opitz Miranda", club: "TALENTOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 11, nombre: "Maria Jesus Medina Bustamante", club: "KUYEN", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 12, nombre: "Florencia Isidora Inostroza Silva", club: "FUTRONO", categoria: "INFANTIL F ML" },
  { banca: "B", n: 12, nombre: "Martina Gabriela Rivera Velasquez", club: "FUTRONO", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 13, nombre: "Ignacia Pinto", club: "GR VALDIVIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 13, nombre: "Matilda Alvarado Ruiz", club: "OHIGGINS", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 14, nombre: "Isabella Higuera", club: "GR VALDIVIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 14, nombre: "Noemi Gonzalez Kahler", club: "INTI LOS LAGOS", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 15, nombre: "Javiera Morales Mulato", club: "CHAYTOR", categoria: "INFANTIL F ML" },
  { banca: "B", n: 15, nombre: "Rosario Romero", club: "CAH", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 16, nombre: "Josefa Contreras", club: "GR VALDIVIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 16, nombre: "Sofia Cardenas", club: "NOVA STELLA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 17, nombre: "Josefa Wachter Schrag", club: "AMARANTA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 17, nombre: "Sofia Ignacia Andrades Munoz", club: "R.ESPANOLA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 18, nombre: "Julieta Sofia Cabezas Alday", club: "ORIGENES", categoria: "INFANTIL F ML" },
  { banca: "B", n: 18, nombre: "Amaral Andrade", club: "NOVA STELLA", categoria: "SENIOR A BALON" },
  { banca: "A", n: 19, nombre: "Laura Hornig Fischer", club: "INTI LOS LAGOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 19, nombre: "Antonia Becerra Garcia", club: "AMARANTA", categoria: "SENIOR A BALON" },
  { banca: "A", n: 20, nombre: "Mailen Asenjo Cardenas", club: "INTI LOS LAGOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 20, nombre: "Constanza Belen Carrasco Milanca", club: "AMARANTA", categoria: "SENIOR A BALON" },
  { banca: "A", n: 21, nombre: "Maite Lara", club: "GERMANIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 21, nombre: "Antonella Constanza Vegas Godoy", club: "AMULEN", categoria: "SENIOR A BALON" },
  { banca: "A", n: 22, nombre: "Millaray Angelita Aravena Hernandez", club: "PAILLACO", categoria: "INFANTIL F ML" },
  { banca: "B", n: 22, nombre: "Consuelo Emilia Torres Rivera", club: "AMULEN", categoria: "SENIOR A BALON" },
  { banca: "A", n: 23, nombre: "Montserrat Anahi Arias Zevallos", club: "PAILLACO", categoria: "INFANTIL F ML" },
  { banca: "B", n: 23, nombre: "Emily Margoth Ramos Mella", club: "AMULEN", categoria: "SENIOR A BALON" },
  { banca: "A", n: 24, nombre: "Olivia Gallardo Collinao", club: "CHAYTOR", categoria: "INFANTIL F ML" },
  { banca: "B", n: 24, nombre: "Josefa Valentina Figueroa Aguilera", club: "AMULEN", categoria: "SENIOR A BALON" },
  { banca: "A", n: 25, nombre: "Pascale", club: "KUYEN", categoria: "INFANTIL F ML" },
  { banca: "B", n: 25, nombre: "Sofia Isidora Fonseca Avila", club: "AMULEN", categoria: "SENIOR A BALON" }
];
