export const sabado = [
  { banca: "A", n: 1, nombre: "Agustina Ignacia Garrido Miranda", club: "HUELLAS", categoria: "MINI F ML" },
  { banca: "B", n: 1, nombre: "Victoria Wilde Garrido", club: "CISNES", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 2, nombre: "Agustina Pia Schafer Banados", club: "PAILLACO", categoria: "MINI F ML" },
  { banca: "B", n: 2, nombre: "Valentina Rebolledo", club: "ALMA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 3, nombre: "Alba Simone Vives Hidalgo", club: "PAILLACO", categoria: "MINI F ML" },
  { banca: "B", n: 3, nombre: "Valentina Isabella Carrillo Henriquez", club: "AMARANTA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 4, nombre: "Alondra Valentina Acevedo Gatica", club: "FUTRONO", categoria: "MINI F ML" },
  { banca: "B", n: 4, nombre: "Stephanie Nicole Monroy Maldonado", club: "AMULEN", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 5, nombre: "Amanda Aguilera", club: "GREENHOUSE", categoria: "MINI F ML" },
  { banca: "B", n: 5, nombre: "Sophia Vollmer Tenorio", club: "TALENTOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 6, nombre: "Amanda Ysabel Godoy Briceno", club: "ELITE", categoria: "MINI F ML" },
  { banca: "B", n: 6, nombre: "Sophia Gomez Mellado", club: "TALENTOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 7, nombre: "Amira Leticia Velazco Acosta", club: "ORIGENES", categoria: "MINI F ML" },
  { banca: "B", n: 7, nombre: "Sofia Nercelles", club: "PAILLACO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 8, nombre: "Antonella Giacomozzi Vera", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 8, nombre: "Sofia Munoz Toledo", club: "CAH", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 9, nombre: "Antonia Fonseca Vera", club: "CHAYTOR", categoria: "MINI F ML" },
  { banca: "B", n: 9, nombre: "Sofia Antonella Gonzalez Perez", club: "PAILLACO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 10, nombre: "Arantza Yuliet Yumar Lobo", club: "ELITE", categoria: "MINI F ML" },
  { banca: "B", n: 10, nombre: "Renata Isidora Cobos Ili", club: "PAILLACO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 11, nombre: "Barbara Zuniga Mancilla", club: "TRAVESIA", categoria: "MINI F ML" },
  { banca: "B", n: 11, nombre: "Pia Torres Zamorano", club: "CHAYTOR", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 12, nombre: "Begona Arrigorriaga Pinto", club: "CHAYTOR", categoria: "MINI F ML" },
  { banca: "B", n: 12, nombre: "Monserrat Contreras Tejos", club: "GR LAUTARO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 13, nombre: "Carlota Daniella Gutierrez Camargo", club: "ELITE", categoria: "MINI F ML" },
  { banca: "B", n: 13, nombre: "Matilde De Jourdan Carrillo", club: "ALEMAN VILLARRICA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 14, nombre: "Colomba Thomas Leiva", club: "FRESIA", categoria: "MINI F ML" },
  { banca: "B", n: 14, nombre: "Matilda Nett Navarrete", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 15, nombre: "Ema Alejandra Quiyinao Barrientos", club: "ORIGENES", categoria: "MINI F ML" },
  { banca: "B", n: 15, nombre: "Matilda Dumenes Rojas", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 16, nombre: "Emilia Antonela Carcamo Quezada", club: "PAILLACO", categoria: "MINI F ML" },
  { banca: "B", n: 16, nombre: "Martina Miralles", club: "GR VALDIVIA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 17, nombre: "Emilia Navarrete Tillemann", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 17, nombre: "Maithe Aguilar Rodriguez", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 18, nombre: "Emma Catalina Baeza Aguilera", club: "ORIGENES", categoria: "MINI F ML" },
  { banca: "B", n: 18, nombre: "Maite Nunez Fernandez", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 19, nombre: "Emma Victoria Luengo Chacon", club: "R.ESPANOLA", categoria: "MINI F ML" },
  { banca: "B", n: 19, nombre: "Magdalena Calisto Cisterna", club: "TRAVESIA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 20, nombre: "Florencia Isidora Millar Navarrete", club: "AMULEN", categoria: "MINI F ML" },
  { banca: "B", n: 20, nombre: "Laura Paz Hernandez Saez", club: "HUELLAS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 21, nombre: "Gretta Gonzalez Pineda", club: "PAILLACO", categoria: "MINI F ML" },
  { banca: "B", n: 21, nombre: "Laura Duran Werth", club: "ALEMAN VILLARRICA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 22, nombre: "Helena Yanez Munoz", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 22, nombre: "Josefina Vasquez Sayeg", club: "TALENTOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 23, nombre: "Ignacia Araya", club: "GR VALDIVIA", categoria: "MINI F ML" },
  { banca: "B", n: 23, nombre: "Josefina Pauline Schafer Banados", club: "PAILLACO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 24, nombre: "Ignacia Barrientos Rubio", club: "FRESIA", categoria: "MINI F ML" },
  { banca: "B", n: 24, nombre: "Josefa Verdello", club: "GREENHOUSE", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 25, nombre: "Ignacia Pedrero Herrera", club: "TALENTOS", categoria: "MINI F ML" },
  { banca: "B", n: 25, nombre: "Josefa Admore Jaduri Cardenas", club: "PAILLACO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 26, nombre: "Isidora Farina Cardenas", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 26, nombre: "Javiera Saavedra Santos", club: "TALENTOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 27, nombre: "Isidora Medina Andrades", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 27, nombre: "Isidora Jimenez", club: "GREENHOUSE", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 28, nombre: "Isis Elisa Yanez Poveda", club: "CAH", categoria: "MINI F ML" },
  { banca: "B", n: 28, nombre: "Isidora Cespedez", club: "GREENHOUSE", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 29, nombre: "Jacinta Larrain Painemal", club: "CHAYTOR", categoria: "MINI F ML" },
  { banca: "B", n: 29, nombre: "Isabella Alexandra Lagos Carrasco", club: "R.ESPANOLA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 30, nombre: "Joaquina Masias Duarte", club: "TALENTOS", categoria: "MINI F ML" },
  { banca: "B", n: 30, nombre: "Genesis Hernandez Martinez", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 31, nombre: "Julieta Silva Rojas", club: "GR LAUTARO", categoria: "MINI F ML" },
  { banca: "B", n: 31, nombre: "Florencia Villa", club: "GREENHOUSE", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 32, nombre: "Leonor Diaz Shaefer", club: "FRESIA", categoria: "MINI F ML" },
  { banca: "B", n: 32, nombre: "Florencia Jaramillo Echeverria", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 33, nombre: "Leonor Gutierrez Abarzua", club: "CHAYTOR", categoria: "MINI F ML" },
  { banca: "B", n: 33, nombre: "Florencia Gallardo", club: "GR VALDIVIA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 34, nombre: "Maria Gracia Silva Vergara", club: "ALEMAN VILLARRICA", categoria: "MINI F ML" },
  { banca: "B", n: 34, nombre: "Fernanda Carolina Navarrete Rademacher", club: "HUELLAS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 35, nombre: "Maria Victoria Cortes", club: "AMARANTA", categoria: "MINI F ML" },
  { banca: "B", n: 35, nombre: "Fernanda Avila Carrasco", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 36, nombre: "Pia Garces Pizarro", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 36, nombre: "Emily Ayelen Espinoza Garces", club: "AMULEN", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 37, nombre: "Rocio Tapia Castaneda", club: "TALENTOS", categoria: "MINI F ML" },
  { banca: "B", n: 37, nombre: "Emilia Obando", club: "GR VALDIVIA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 38, nombre: "Sharlot Gimena Caldera Alvarez", club: "OLYMPUS", categoria: "MINI F ML" },
  { banca: "B", n: 38, nombre: "Emilia Antonia Tejo Montes", club: "PAILLACO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 39, nombre: "Sofia Carrasco Silva", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 39, nombre: "Belen Medina Pizarro", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 40, nombre: "Trinidad Montenegro", club: "GR VALDIVIA", categoria: "MINI F ML" },
  { banca: "B", n: 40, nombre: "Asuncion Teuber", club: "GERMANIA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 41, nombre: "Trinidad Sagredo Silva", club: "TRAVESIA", categoria: "MINI F ML" },
  { banca: "B", n: 41, nombre: "Antonia Sandoval Alvarado", club: "TALENTOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 42, nombre: "Valentina Patricia Cardenas Verdugo", club: "AMULEN", categoria: "MINI F ML" },
  { banca: "B", n: 42, nombre: "Antonia Osorio Millalen", club: "GR LAUTARO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 43, nombre: "Valentina Rafaela Lopez Tejeda", club: "OLYMPUS", categoria: "MINI F ML" },
  { banca: "B", n: 43, nombre: "Antonia Hevia Diaz", club: "CHAYTOR", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 44, nombre: "Violeta Hernandez Vergara", club: "GR LAUTARO", categoria: "MINI F ML" },
  { banca: "B", n: 44, nombre: "Antonia Gatica Mendez", club: "ALEMAN VILLARRICA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 45, nombre: "Valentina Gonzalez Flores", club: "ALMA", categoria: "TC F ML" },
  { banca: "B", n: 45, nombre: "Antonella Delgado Barria", club: "TRAVESIA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 46, nombre: "Valentina Alejandra Cotal Villanueva", club: "PAILLACO", categoria: "TC F ML" },
  { banca: "B", n: 46, nombre: "Antonella Cofre Conoman", club: "AMULEN", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 47, nombre: "Sofia Alvarez Alve", club: "ALMA", categoria: "TC F ML" },
  { banca: "B", n: 47, nombre: "Amanda Sumps Socias", club: "ALEMAN VILLARRICA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 48, nombre: "Rebeca Schwerter Thiers", club: "ALEMAN TEMUCO", categoria: "TC F ML" },
  { banca: "B", n: 48, nombre: "Amanda Cayulef", club: "CAH", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 49, nombre: "Mila Ignacia Tilleria Ponce", club: "ORIGENES", categoria: "TC F ML" },
  { banca: "B", n: 49, nombre: "Agustina Romero", club: "CAH", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 50, nombre: "Maria Javiera Negroni", club: "ALMA", categoria: "TC F ML" },
  { banca: "B", n: 50, nombre: "Agustina Lagos", club: "GREENHOUSE", categoria: "PEQUE F ML" },
  { banca: "A", n: 51, nombre: "Josefa Vidal Cid", club: "GR LAUTARO", categoria: "TC F ML" },
  { banca: "B", n: 51, nombre: "Antonia Martina Garcia Navarro", club: "AMARANTA", categoria: "PEQUE F ML" },
  { banca: "A", n: 52, nombre: "Josefa Trinidad Sepulveda Lobos", club: "AMARANTA", categoria: "TC F ML" },
  { banca: "B", n: 52, nombre: "Aurora Sofia Fischer Michaelis", club: "AMARANTA", categoria: "PEQUE F ML" },
  { banca: "A", n: 53, nombre: "Josefa Leonor Ormazabal Andrade", club: "ELITE", categoria: "TC F ML" },
  { banca: "B", n: 53, nombre: "Blanca Stubing Neumann", club: "ALEMAN TEMUCO", categoria: "PEQUE F ML" },
  { banca: "A", n: 54, nombre: "Florencia Vergara", club: "GR VALDIVIA", categoria: "TC F ML" },
  { banca: "B", n: 54, nombre: "Carolina Torres Zamorano", club: "CHAYTOR", categoria: "PEQUE F ML" },
  { banca: "A", n: 55, nombre: "Fernanda Reyes", club: "GR VALDIVIA", categoria: "TC F ML" },
  { banca: "B", n: 55, nombre: "Emma Ignacia Mayorga Gomez", club: "AMARANTA", categoria: "PEQUE F ML" },
  { banca: "A", n: 56, nombre: "Antonia Munoz", club: "GR VALDIVIA", categoria: "TC F ML" },
  { banca: "B", n: 56, nombre: "Esmeralda Casanueva Ibanez", club: "AMARANTA", categoria: "PEQUE F ML" },
  { banca: "A", n: 57, nombre: "Antonia Catalina Solis Gonzalez", club: "ARA", categoria: "TC F ML" },
  { banca: "B", n: 57, nombre: "Isabella Barriga", club: "NOVA STELLA", categoria: "PEQUE F ML" },
  { banca: "A", n: 58, nombre: "Antonella Dominga Vergara Ruiz", club: "R.ESPANOLA", categoria: "TC F ML" },
  { banca: "B", n: 58, nombre: "Isidora Bollman Jaramillo", club: "GR LAUTARO", categoria: "PEQUE F ML" },
  { banca: "A", n: 59, nombre: "Amanda Gomez", club: "CAH", categoria: "TC F ML" },
  { banca: "B", n: 59, nombre: "Isidora Caamano Gutierrez", club: "ALEMAN TEMUCO", categoria: "PEQUE F ML" },
  { banca: "A", n: 60, nombre: "Agustina Monserrat Salinas Urrutia", club: "R.ESPANOLA", categoria: "TC F ML" },
  { banca: "B", n: 60, nombre: "Isidora Teuber Gonzalez", club: "ALEMAN TEMUCO", categoria: "PEQUE F ML" },
  { banca: "A", n: 61, nombre: "Ambar Astroza", club: "OHIGGINS", categoria: "PEQUE C ML" },
  { banca: "B", n: 61, nombre: "Josefa Larrain Painemal", club: "CHAYTOR", categoria: "PEQUE F ML" },
  { banca: "A", n: 62, nombre: "Magdalena Oyarzo Beltran", club: "OHIGGINS", categoria: "PEQUE C ML" },
  { banca: "B", n: 62, nombre: "Marianna Pena Sepulveda", club: "CISNES", categoria: "PEQUE F ML" },
  { banca: "A", n: 63, nombre: "Maite Vargas Lerchundi", club: "ALMA", categoria: "PEQUE C ML" },
  { banca: "B", n: 63, nombre: "Matilde Antonia Rivera Figueroa", club: "AMARANTA", categoria: "PEQUE F ML" },
  { banca: "A", n: 64, nombre: "Sofia Valenzuela", club: "OHIGGINS", categoria: "PEQUE C ML" },
  { banca: "B", n: 64, nombre: "Mia Hoffmann Canete", club: "R.ESPANOLA", categoria: "PEQUE F ML" },

  { banca: "A", n: 1, nombre: "Violeta Manzano Mora", club: "TALENTOS", categoria: "INFANTIL C ML" },
  { banca: "B", n: 1, nombre: "Tatiana Tapia Bize", club: "TALENTOS", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 2, nombre: "Valentina Arellano Beroiza", club: "GR LAUTARO", categoria: "INFANTIL C ML" },
  { banca: "B", n: 2, nombre: "Adalys Pascale Pulido Rolack", club: "HUELLAS", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 3, nombre: "Sofia Victoria Fuentes Huechante", club: "HUELLAS", categoria: "INFANTIL C ML" },
  { banca: "B", n: 3, nombre: "Agustina Isidora Sanchez Varela", club: "ELITE", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 4, nombre: "Sofia Rehl Puentes", club: "CHAYTOR", categoria: "INFANTIL C ML" },
  { banca: "B", n: 4, nombre: "Amanda Diaz", club: "ARA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 5, nombre: "Sofia Pereira Gatica", club: "CISNES", categoria: "INFANTIL C ML" },
  { banca: "B", n: 5, nombre: "Amara Pendola Amoros", club: "R.ESPANOLA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 6, nombre: "Sofia Fernandez", club: "GR VALDIVIA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 6, nombre: "Amelia Antonia San Martin Mellado", club: "ELITE", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 7, nombre: "Sofia Elizabeth Pacheco Valenzuela", club: "ORIGENES", categoria: "INFANTIL C ML" },
  { banca: "B", n: 7, nombre: "Anais Pineda Lopez", club: "ARA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 8, nombre: "Simona Eliana Riquelme Angulo", club: "ELITE", categoria: "INFANTIL C ML" },
  { banca: "B", n: 8, nombre: "Ayalen Flores Munoz", club: "OHIGGINS", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 9, nombre: "Rafaela Nunez Burrows", club: "CAH", categoria: "INFANTIL C ML" },
  { banca: "B", n: 9, nombre: "Catalina Lima", club: "GR VALDIVIA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 10, nombre: "Pascal Ordenes Vargas", club: "ALMA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 10, nombre: "Elena Antonia Puebla Leiva", club: "ORIGENES", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 11, nombre: "Mariapaz Antonia Munoz Jara", club: "AMULEN", categoria: "INFANTIL C ML" },
  { banca: "B", n: 11, nombre: "Emma Antonia Penafiel Lopez", club: "PAILLACO", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 12, nombre: "Maite Ignacia Navarrete Venegas", club: "ALMA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 12, nombre: "Fernanda Isabel Carolina Iturra Garnica", club: "AMULEN", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 13, nombre: "Ma. Fernanda Valenzuela Vera", club: "AMARANTA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 13, nombre: "Fernanda Rayen Velasques San Martin", club: "AMARANTA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 14, nombre: "Lucia Gumiel Bascunan", club: "ALEMAN TEMUCO", categoria: "INFANTIL C ML" },
  { banca: "B", n: 14, nombre: "Florencia Isidora Acuna Bahamondes", club: "KUYEN", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 15, nombre: "Leonor Cifuentes Carvajal", club: "ALMA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 15, nombre: "Florencia Santos Cortes", club: "CAH", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 16, nombre: "Julieta Candia Arancibia", club: "CISNES", categoria: "INFANTIL C ML" },
  { banca: "B", n: 16, nombre: "Francisca Baeza Jaque", club: "CAH", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 17, nombre: "Javiera Manriquez Salinas", club: "ALMA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 17, nombre: "Isidora Agustina Perez Luna", club: "ELITE", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 18, nombre: "Javiera Jara Iturrieta", club: "CHAYTOR", categoria: "INFANTIL C ML" },
  { banca: "B", n: 18, nombre: "Isidora Belen Nercelles Castro", club: "PAILLACO", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 19, nombre: "Jasmin Martinez", club: "ARA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 19, nombre: "Isidora Ignacia Ceron Pacheco", club: "OLYMPUS", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 20, nombre: "Isidora Mellado Rojas", club: "ARA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 20, nombre: "Isidora Millas", club: "GR VALDIVIA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 21, nombre: "Isabella Mella", club: "GR VALDIVIA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 21, nombre: "Josefa Caceres", club: "GR VALDIVIA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 22, nombre: "Isabel Mendez Cisterna", club: "CAH", categoria: "INFANTIL C ML" },
  { banca: "B", n: 22, nombre: "Josefa Emilia Salgado Ortega", club: "R.ESPANOLA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 23, nombre: "Ignacia Munoz", club: "GR VALDIVIA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 23, nombre: "Josefa Ferron", club: "NOVA STELLA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 24, nombre: "Ignacia Flores Noli", club: "CHAYTOR", categoria: "INFANTIL C ML" },
  { banca: "B", n: 24, nombre: "Josefina De La Parra Mendez", club: "R.ESPANOLA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 25, nombre: "Genesis Cocio", club: "AMARANTA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 25, nombre: "Juliana Leonor Vives Hidalgo", club: "PAILLACO", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 26, nombre: "Florencia Isabella Munoz Ramirez", club: "R.ESPANOLA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 26, nombre: "Julieta Gaete", club: "AMARANTA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 27, nombre: "Florencia Aguila", club: "GR VALDIVIA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 27, nombre: "Julieta Ignacia Quezada Martinez", club: "ARA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 28, nombre: "Emilia Renata Bustos Barrientos", club: "ORIGENES", categoria: "INFANTIL C ML" },
  { banca: "B", n: 28, nombre: "Luciana Antonia Miranda Vergara", club: "ARA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 29, nombre: "Elisa Mariana Palma Grob", club: "ELITE", categoria: "INFANTIL C ML" },
  { banca: "B", n: 29, nombre: "Magdalena Alicia Yelor Mora", club: "FUTRONO", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 30, nombre: "Blanca Caro", club: "KUYEN", categoria: "INFANTIL C ML" },
  { banca: "B", n: 30, nombre: "Maite Perez", club: "GR VALDIVIA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 31, nombre: "Belen Aros", club: "NOVA STELLA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 31, nombre: "Maite Rain Altamirano", club: "ALMA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 32, nombre: "Aylin Pastene Valdebenito", club: "TALENTOS", categoria: "INFANTIL C ML" },
  { banca: "B", n: 32, nombre: "Maria Ignacia Collipal Herrera", club: "ARA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 33, nombre: "Aylin Astroza", club: "OHIGGINS", categoria: "INFANTIL C ML" },
  { banca: "B", n: 33, nombre: "Maria Jesus Araneda Del Rio", club: "ALEMAN TEMUCO", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 34, nombre: "Antonietta Josefina Molina Paredes", club: "OLYMPUS", categoria: "INFANTIL C ML" },
  { banca: "B", n: 34, nombre: "Maria Silva", club: "ARA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 35, nombre: "Antonia Paz Obreque Bachsmann", club: "ARA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 35, nombre: "Martina Montecinos Andrade", club: "INTI LOS LAGOS", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 36, nombre: "Antonia Paz Fuenzalida Cofre", club: "ORIGENES", categoria: "INFANTIL C ML" },
  { banca: "B", n: 36, nombre: "Matilde Victoria Valenzuela Gonzales", club: "ORIGENES", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 37, nombre: "Antonella Villar Henriquez", club: "ALMA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 37, nombre: "Mia Isabella Foitzick Ahumada", club: "PAILLACO", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 38, nombre: "Antonella Aranza Cortez Hernandez", club: "FRESIA", categoria: "INFANTIL C ML" },
  { banca: "B", n: 38, nombre: "Pascale Gabrielle Suart Molina", club: "ARA", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 39, nombre: "Amanda Fuentes", club: "KUYEN", categoria: "INFANTIL C ML" },
  { banca: "B", n: 39, nombre: "Pia Araneda Matus", club: "CHAYTOR", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 40, nombre: "Alba Amara Florencia Campos Ojeda", club: "AMULEN", categoria: "INFANTIL C ML" },
  { banca: "B", n: 40, nombre: "Sofia Alejandra Rodas Aguilera", club: "ELITE", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 41, nombre: "Agustina Manriquez", club: "ALMA", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 41, nombre: "Sofia Matus Munoz", club: "ALEMAN TEMUCO", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 42, nombre: "Anais Antonella Lagos Albornoz", club: "R.ESPANOLA", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 42, nombre: "Valentina Isabel Quezada Burgos", club: "PAILLACO", categoria: "PREINFANTIL C ML" },
  { banca: "A", n: 43, nombre: "Anisa Telias Saez", club: "ORIGENES", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 43, nombre: "Trinidad Amparo Carcamo Martinez", club: "AMARANTA", categoria: "MINI C" },
  { banca: "A", n: 44, nombre: "Antonella Monserrat Monsalvez Lefno", club: "HUELLAS", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 44, nombre: "Sofia Pulgar", club: "GR VALDIVIA", categoria: "MINI C" },
  { banca: "A", n: 45, nombre: "Barbara Scarleth Dominguez Manque", club: "OLYMPUS", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 45, nombre: "Pascal Ignacia Aillal Perez", club: "AMULEN", categoria: "MINI C" },
  { banca: "A", n: 46, nombre: "Blanca Valenzuela Candia", club: "ALEMAN TEMUCO", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 46, nombre: "Martina Santos Cortes", club: "CAH", categoria: "MINI C" },
  { banca: "A", n: 47, nombre: "Camila Brintrup Saez", club: "TALENTOS", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 47, nombre: "Maria-Agustina Ortiz Ramos", club: "GR LAUTARO", categoria: "MINI C" },
  { banca: "A", n: 48, nombre: "Clara Mondragon", club: "OHIGGINS", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 48, nombre: "Maria Del Pilar Cortes Arriagada", club: "AMARANTA", categoria: "MINI C" },
  { banca: "A", n: 49, nombre: "Cristina Morales Barria", club: "INTI LOS LAGOS", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 49, nombre: "Maite Isidora Rivera Diaz", club: "R.ESPANOLA", categoria: "MINI C" },
  { banca: "A", n: 50, nombre: "Elisa Noriega Rojo", club: "ALEMAN VILLARRICA", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 50, nombre: "Magdalena Aurora Munoz Cardenas", club: "OLYMPUS", categoria: "MINI C" },
  { banca: "A", n: 51, nombre: "Elisa Torres Marquez", club: "TALENTOS", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 51, nombre: "Mackenzie Valentina Yurisch Vasquez", club: "ARA", categoria: "MINI C" },
  { banca: "A", n: 52, nombre: "Emilia Uribe Vargas", club: "ALMA", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 52, nombre: "Luciana Paz Guzman Vera", club: "FRESIA", categoria: "MINI C" },
  { banca: "A", n: 53, nombre: "Eymily Sofia Avendano Rubilar", club: "KUYEN", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 53, nombre: "Leonor Antonia Ortiz Villarroel", club: "AMULEN", categoria: "MINI C" },
  { banca: "A", n: 54, nombre: "Javiera Abarzua Guzman", club: "ALEMAN TEMUCO", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 54, nombre: "Laura Gallardo Alvarado", club: "OHIGGINS", categoria: "MINI C" },
  { banca: "A", n: 55, nombre: "Javiera Puente Monsalves", club: "CHAYTOR", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 55, nombre: "Jacinta Barckhahn", club: "NOVA STELLA", categoria: "MINI C" },
  { banca: "A", n: 56, nombre: "Josefina Leonor Guzman Cardenas", club: "ELITE", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 56, nombre: "Isabel Aravena Arismendi", club: "FUTRONO", categoria: "MINI C" },
  { banca: "A", n: 57, nombre: "Josefina Palominos Moreno", club: "ALEMAN VILLARRICA", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 57, nombre: "Francisca Henning Fica", club: "ALEMAN TEMUCO", categoria: "MINI C" },
  { banca: "A", n: 58, nombre: "Lucia Josefina Fuentes Huechante", club: "HUELLAS", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 58, nombre: "Florencia Odette Barria Vial", club: "ELITE", categoria: "MINI C" },
  { banca: "A", n: 59, nombre: "Maria Jose Orellana", club: "KUYEN", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 59, nombre: "Florencia Lucia Caliva Herrera", club: "R.ESPANOLA", categoria: "MINI C" },
  { banca: "A", n: 60, nombre: "Nirvanna Emmy De Nobrega Martinez", club: "KUYEN", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 60, nombre: "Florencia Isidora Pardo Marquez", club: "HUELLAS", categoria: "MINI C" },
  { banca: "A", n: 61, nombre: "Renata Diez", club: "NOVA STELLA", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 61, nombre: "Fiorella Romero Ziliani", club: "AMARANTA", categoria: "MINI C" },
  { banca: "A", n: 62, nombre: "Valentina Emilia Vargas Munoz", club: "R.ESPANOLA", categoria: "JUNIOR C ARO" },
  { banca: "B", n: 62, nombre: "Dulce Rios", club: "AMARANTA", categoria: "MINI C" },
  { banca: "A", n: 63, nombre: "Renata Ignacia Jara Bahamonde", club: "ARA", categoria: "AC2 A ML" },
  { banca: "B", n: 63, nombre: "Catalina Kenner Ose", club: "CISNES", categoria: "MINI C" },
  { banca: "A", n: 64, nombre: "Luciana Relhs Puente", club: "ARA", categoria: "AC2 A ML" },
  { banca: "B", n: 64, nombre: "Carliannys Salas Moreno", club: "GR LAUTARO", categoria: "MINI C" },
  { banca: "A", n: 65, nombre: "Leonor Damiani Diaz", club: "INTI LOS LAGOS", categoria: "AC2 A ML" },
  { banca: "B", n: 65, nombre: "Antonella Pacheco", club: "NOVA STELLA", categoria: "MINI C" },
  { banca: "A", n: 66, nombre: "Elise Sophia Paredes Briesmaster", club: "ARA", categoria: "AC2 A ML" },
  { banca: "B", n: 66, nombre: "Amanda Jesus Danae Quijon Lara", club: "NOVA STELLA", categoria: "MINI C" },
  { banca: "A", n: 67, nombre: "Anais Aylen Mansilla Ortega", club: "FRESIA", categoria: "AC2 A ML" },
  { banca: "B", n: 67, nombre: "Amanda Isidora Bravo Levin", club: "OLYMPUS", categoria: "MINI C" },
  { banca: "A", n: 68, nombre: "Agustina Adelie Iturra Perez", club: "AMARANTA", categoria: "MINI C" },

  { banca: "A", n: 1, nombre: "Valentina Gonzalez Flores", club: "ALMA", categoria: "TC F ML" },
  { banca: "B", n: 1, nombre: "Renata Ignacia Jara Bahamonde", club: "ARA", categoria: "AC2 A ML" },
  { banca: "A", n: 2, nombre: "Sofia Alvarez Alve", club: "ALMA", categoria: "TC F ML" },
  { banca: "B", n: 2, nombre: "Luciana Relhs Puente", club: "ARA", categoria: "AC2 A ML" },
  { banca: "A", n: 3, nombre: "Rebeca Schwerter Thiers", club: "ALEMAN TEMUCO", categoria: "TC F ML" },
  { banca: "B", n: 3, nombre: "Leonor Damiani Diaz", club: "INTI LOS LAGOS", categoria: "AC2 A ML" },
  { banca: "A", n: 4, nombre: "Mila Ignacia Tilleria Ponce", club: "ORIGENES", categoria: "TC F ML" },
  { banca: "B", n: 4, nombre: "Elise Sophia Paredes Briesmaster", club: "ARA", categoria: "AC2 A ML" },
  { banca: "A", n: 5, nombre: "Maria Javiera Negroni", club: "ALMA", categoria: "TC F ML" },
  { banca: "B", n: 5, nombre: "Anais Aylen Mansilla Ortega", club: "FRESIA", categoria: "AC2 A ML" },
  { banca: "A", n: 6, nombre: "Josefa Vidal Cid", club: "GR LAUTARO", categoria: "TC F ML" },
  { banca: "B", n: 6, nombre: "Valentina Ramirez", club: "AMATISTA", categoria: "SENIOR B ARO" },
  { banca: "A", n: 7, nombre: "Josefa Trinidad Sepulveda Lobos", club: "AMARANTA", categoria: "TC F ML" },
  { banca: "B", n: 7, nombre: "Valentina Beatriz Ojeda Soto", club: "AZUCENAS", categoria: "SENIOR B ARO" },
  { banca: "A", n: 8, nombre: "Josefa Leonor Ormazabal Andrade", club: "ELITE", categoria: "TC F ML" },
  { banca: "B", n: 8, nombre: "Emiliana Javiera Uribe Mancilla", club: "AZUCENAS", categoria: "SENIOR B ARO" },
  { banca: "A", n: 9, nombre: "Florencia Vergara", club: "GR VALDIVIA", categoria: "TC F ML" },
  { banca: "B", n: 9, nombre: "Antonia Angelina Velasquez Alarcon", club: "FRESIA", categoria: "SENIOR B ARO" },
  { banca: "A", n: 10, nombre: "Fernanda Reyes", club: "GR VALDIVIA", categoria: "TC F ML" },
  { banca: "B", n: 10, nombre: "Antonia Sanchez", club: "KUYEN", categoria: "SENIOR B ARO" },
  { banca: "A", n: 11, nombre: "Antonia Munoz", club: "GR VALDIVIA", categoria: "TC F ML" },
  { banca: "B", n: 11, nombre: "Fernanda Rivera Velazques", club: "TALENTOS", categoria: "SENIOR B ARO" },
  { banca: "A", n: 12, nombre: "Antonia Catalina Solis Gonzalez", club: "ARA", categoria: "TC F ML" },
  { banca: "B", n: 12, nombre: "Florencia Angelica Sanchez Ulloa", club: "AMULEN", categoria: "SENIOR B ARO" },
  { banca: "A", n: 13, nombre: "Antonella Dominga Vergara Ruiz", club: "R.ESPANOLA", categoria: "TC F ML" },
  { banca: "B", n: 13, nombre: "Javiera Mery", club: "NOVA STELLA", categoria: "SENIOR B ARO" },
  { banca: "A", n: 14, nombre: "Amanda Gomez", club: "CAH", categoria: "TC F ML" },
  { banca: "B", n: 14, nombre: "Karen Sophia Betancurt Vera", club: "FUTRONO", categoria: "SENIOR B ARO" },
  { banca: "A", n: 15, nombre: "Agustina Monserrat Salinas Urrutia", club: "R.ESPANOLA", categoria: "TC F ML" },
  { banca: "B", n: 15, nombre: "Pascale Isabella Poblete Rojas", club: "KUYEN", categoria: "SENIOR B ARO" },
  { banca: "A", n: 16, nombre: "Monserrat San martin", club: "AMATISTA", categoria: "SENIOR C ARO" },
  { banca: "B", n: 16, nombre: "Pia De Los Angeles Martinez Salazar", club: "KUYEN", categoria: "SENIOR B ARO" },
  { banca: "A", n: 17, nombre: "Magdalena Navarete", club: "WINDSOR", categoria: "SENIOR C ARO" },
  { banca: "B", n: 17, nombre: "Rayen Nahuel Poblete", club: "CISNES", categoria: "SENIOR B ARO" },
  { banca: "A", n: 18, nombre: "Carmen Sedano", club: "KUYEN", categoria: "SENIOR C ARO" },
  { banca: "B", n: 18, nombre: "Simona Riquelme Fernandez", club: "OHIGGINS", categoria: "SENIOR B ARO" },
  { banca: "A", n: 19, nombre: "Florencia Antonia Acuna Nunez", club: "AMULEN", categoria: "SENIOR C ARO" },
  { banca: "B", n: 19, nombre: "Lissette Montserrat Mendoza Aguilar", club: "AZUCENAS", categoria: "SENIOR B ARO" },
  { banca: "A", n: 20, nombre: "Florencia Caifil", club: "GR VALDIVIA", categoria: "SENIOR C ARO" },
  { banca: "B", n: 20, nombre: "Yennifer Aguilar Rojas", club: "INTI LOS LAGOS", categoria: "SENIOR B ARO" },
  { banca: "A", n: 21, nombre: "Francisca Belen Canulef Barrientos", club: "OLYMPUS", categoria: "SENIOR C ARO" },
  { banca: "B", n: 21, nombre: "Amanda Martinez Vargas", club: "TALENTOS", categoria: "AC3 A ARO" },
  { banca: "A", n: 22, nombre: "Maria Jesus Vega Prado", club: "R.ESPANOLA", categoria: "SENIOR C ARO" },
  { banca: "B", n: 22, nombre: "Constanza Sandoval", club: "ORIGENES", categoria: "AC3 A ARO" },
  { banca: "A", n: 23, nombre: "Maria Jose Pena Sepulveda", club: "CISNES", categoria: "SENIOR C ARO" },
  { banca: "B", n: 23, nombre: "Matilda Silva Maldonado", club: "TALENTOS", categoria: "AC3 A ARO" },
  { banca: "A", n: 24, nombre: "Maria Jose Yelor Mora", club: "FUTRONO", categoria: "SENIOR C ARO" },
  { banca: "B", n: 24, nombre: "Maria Valentina Suarez Mendoza", club: "ORIGENES", categoria: "AC3 A ARO" },
  { banca: "A", n: 25, nombre: "Martina Vargas Lerchundi", club: "ALMA", categoria: "SENIOR C ARO" },
  { banca: "B", n: 25, nombre: "Josefa Agustina Calfuquir Villegas", club: "AMARANTA", categoria: "AC3 A ARO" },
  { banca: "A", n: 26, nombre: "Tahis Cancino", club: "OHIGGINS", categoria: "SENIOR C ARO" },
  { banca: "B", n: 26, nombre: "Anais Aylen Mansilla Ortega", club: "FRESIA", categoria: "AC2 A CUERDA" },
  { banca: "A", n: 27, nombre: "Valentina Andrea Valenzuela Henriquez", club: "FUTRONO", categoria: "SENIOR C ARO" },
  { banca: "B", n: 27, nombre: "Elise Sophia Paredes Briesmaster", club: "ARA", categoria: "AC2 A CUERDA" },
  { banca: "A", n: 28, nombre: "Valentina Catalan Vergara", club: "ALMA", categoria: "SENIOR C ARO" },
  { banca: "B", n: 28, nombre: "Leonor Damiani Diaz", club: "INTI LOS LAGOS", categoria: "AC2 A CUERDA" },
  { banca: "A", n: 29, nombre: "Constanza Sandoval", club: "ORIGENES", categoria: "AC3 A CLAVAS" },
  { banca: "B", n: 29, nombre: "Luciana Relhs puente", club: "ARA", categoria: "AC2 A CUERDA" },
  { banca: "A", n: 30, nombre: "Maria Valentina Suarez", club: "ORIGENES", categoria: "AC3 A CLAVAS" },
  { banca: "B", n: 30, nombre: "Renata Ignacia Jara Bahamonde", club: "ARA", categoria: "AC2 A CUERDA" }
];

export const domingo = [
  { banca: "A", n: 1, nombre: "Agustina Ormazabal", club: "CAH", categoria: "INFANTIL F ML" },
  { banca: "B", n: 1, nombre: "Agustina Chavez Henriquez", club: "OHIGGINS", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 2, nombre: "Agustina Vargas Vara", club: "ALMA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 2, nombre: "Alfonsina Higuera Aburto", club: "ORIGENES", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 3, nombre: "Amelie Schadt Brunner", club: "ALEMAN VILLARRICA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 3, nombre: "Alonsa Ignacia Sandoval Salas", club: "ELITE", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 4, nombre: "Blanca Reinike Duran", club: "ALEMAN VILLARRICA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 4, nombre: "Antonia Florencia Ruiz Bravo", club: "AMARANTA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 5, nombre: "Emilia Antonia Azua Letelier", club: "ARA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 5, nombre: "Antonia Sepulveda", club: "CAH", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 6, nombre: "Emilia Diaz Miranda", club: "TRAVESIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 6, nombre: "Fernanda Javiera Dominguez Manquel", club: "OLYMPUS", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 7, nombre: "Emilia Mora Gaete", club: "TALENTOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 7, nombre: "Javiera Anais Valencia Vallejo", club: "AMARANTA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 8, nombre: "Emily Garate", club: "GR VALDIVIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 8, nombre: "Josefina Ignacia Morales Valenzuela", club: "AMARANTA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 9, nombre: "Emma Schneider Trejo", club: "ALEMAN TEMUCO", categoria: "INFANTIL F ML" },
  { banca: "B", n: 9, nombre: "Llampuzken Raimil", club: "KUYEN", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 10, nombre: "Evelyn Opitz Miranda", club: "TALENTOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 10, nombre: "Maria Jesus Medina Bustamante", club: "KUYEN", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 11, nombre: "Florencia Isidora Inostroza Silva", club: "FUTRONO", categoria: "INFANTIL F ML" },
  { banca: "B", n: 11, nombre: "Martina Gabriela Rivera Velasquez", club: "FUTRONO", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 12, nombre: "Violeta Duran Gacitua", club: "INTI LOS LAGOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 12, nombre: "Mariana Pilar Sagredo Cabezas", club: "AZUCENAS", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 13, nombre: "Zhoe Valentina Flores Martinez", club: "OLYMPUS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 13, nombre: "Matilda Alvarado Ruiz", club: "OHIGGINS", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 14, nombre: "Javiera Morales Mulato", club: "CHAYTOR", categoria: "INFANTIL F ML" },
  { banca: "B", n: 14, nombre: "Noemi Gonzalez Kahler", club: "INTI LOS LAGOS", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 15, nombre: "Josefa Contreras", club: "GR VALDIVIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 15, nombre: "Rosario Romero", club: "CAH", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 16, nombre: "Josefa Wachter Schrag", club: "AMARANTA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 16, nombre: "Sofia Ignacia Andrades Munoz", club: "R.ESPANOLA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 17, nombre: "francisca lemunir", club: "AMATISTA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 17, nombre: "Julieta Salgado", club: "AMATISTA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 18, nombre: "Alexandra Alarcon", club: "AMATISTA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 18, nombre: "Amaral Andrade", club: "NOVA STELLA", categoria: "SENIOR A BALON" },
  { banca: "A", n: 19, nombre: "Rocio Ormazabal", club: "ELITE LOS RIOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 19, nombre: "Antonia Becerra Garcia", club: "AMARANTA", categoria: "SENIOR A BALON" },
  { banca: "A", n: 20, nombre: "Julieta Sofia Cabezas Alday", club: "ORIGENES", categoria: "INFANTIL F ML" },
  { banca: "B", n: 20, nombre: "Constanza Belen Carrasco Milanca", club: "AMARANTA", categoria: "SENIOR A BALON" },
  { banca: "A", n: 21, nombre: "Laura Hornig Fischer", club: "INTI LOS LAGOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 21, nombre: "Antonella Constanza Vegas Godoy", club: "AMULEN", categoria: "SENIOR A BALON" },
  { banca: "A", n: 22, nombre: "Victoria Ruiz", club: "CAH", categoria: "INFANTIL F ML" },
  { banca: "B", n: 22, nombre: "Consuelo Emilia Torres Rivera", club: "AMULEN", categoria: "SENIOR A BALON" },
  { banca: "A", n: 23, nombre: "Maite Lara", club: "GERMANIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 23, nombre: "Emily Margoth Ramos Mella", club: "AMULEN", categoria: "SENIOR A BALON" },
  { banca: "A", n: 24, nombre: "Olivia Gallardo Collinao", club: "CHAYTOR", categoria: "INFANTIL F ML" },
  { banca: "B", n: 24, nombre: "Josefa Valentina Figueroa Aguilera", club: "AMULEN", categoria: "SENIOR A BALON" },
  { banca: "A", n: 25, nombre: "Pascale Manriquez", club: "KUYEN", categoria: "INFANTIL F ML" },
  { banca: "B", n: 25, nombre: "Emily Margoth Ramos Mella", club: "AMULEN", categoria: "SENIOR A BALON" },
  { banca: "A", n: 26, nombre: "Rafaela Carter", club: "GR VALDIVIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 26, nombre: "Josefa Valentina Figueroa Aguilera", club: "AMULEN", categoria: "SENIOR A BALON" },
  { banca: "A", n: 27, nombre: "Renata Aedo Sanchez", club: "TALENTOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 27, nombre: "Martina Sylvana Rodriguez Uribe", club: "OLYMPUS", categoria: "SENIOR A BALON" },
  { banca: "A", n: 28, nombre: "Sofia Springmuller Graeflein", club: "INTI LOS LAGOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 28, nombre: "Sofia Isidora Fonseca Avila", club: "AMULEN", categoria: "SENIOR A BALON" },
  { banca: "A", n: 29, nombre: "Trinidad Solis Reyes", club: "TALENTOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 29, nombre: "Maria Jesus Garrido Uribe", club: "ARA", categoria: "SENIOR A BALON" },
  { banca: "A", n: 30, nombre: "Victoria Martinez Flandez", club: "TALENTOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 30, nombre: "Catalina Fernanda Jaramillo Munoz", club: "ELITE", categoria: "SENIOR A BALON" },
  { banca: "A", n: 31, nombre: "Rafaela Ines Silva Faure", club: "ELITE", categoria: "INFANTIL B ARO" },
  { banca: "B", n: 31, nombre: "Pascal Infante", club: "GR VALDIVIA", categoria: "SENIOR A BALON" },
  { banca: "A", n: 32, nombre: "Moira Pascale Salinas Fontanilla", club: "AMARANTA", categoria: "INFANTIL B ARO" },
  { banca: "B", n: 32, nombre: "Sofia Rozas Zuniga", club: "TALENTOS", categoria: "SENIOR A BALON" },
  { banca: "A", n: 33, nombre: "Kristine Schroeder Ruiz", club: "TALENTOS", categoria: "INFANTIL B ARO" },
  { banca: "B", n: 33, nombre: "Antonia Velasquez Riquelme", club: "R.ESPANOLA", categoria: "SENIOR A CLAVAS" },
  { banca: "A", n: 34, nombre: "Isidora Pascal Luengo Chacon", club: "R.ESPANOLA", categoria: "INFANTIL B ARO" },
  { banca: "B", n: 34, nombre: "Sofia Isidora Fonseca Avila", club: "AMULEN", categoria: "SENIOR A CLAVAS" },
  { banca: "A", n: 35, nombre: "Laura Barckhahn", club: "NOVA STELLA", categoria: "INFANTIL B ARO" },
  { banca: "B", n: 35, nombre: "Pascal Infante", club: "GR VALDIVIA", categoria: "SENIOR A CLAVAS" },
  { banca: "A", n: 36, nombre: "Sofia Cardenas", club: "NOVA STELLA", categoria: "INFANTIL B ARO" },
  { banca: "B", n: 36, nombre: "Martina Sylvana Rodriguez Uribe", club: "OLYMPUS", categoria: "SENIOR A CLAVAS" },
  { banca: "A", n: 37, nombre: "Isidora Belen Paillalef Gutierrez", club: "KUYEN", categoria: "INFANTIL B ARO" },
  { banca: "B", n: 37, nombre: "Patricia Garcia", club: "AMATISTA", categoria: "SENIOR A CLAVAS" },
  { banca: "A", n: 38, nombre: "Isidora Antonia Asenjo Diaz", club: "AMARANTA", categoria: "INFANTIL B ARO" },
  { banca: "B", n: 38, nombre: "Josefa Valentina Figueroa Aguilera", club: "AMULEN", categoria: "SENIOR A CLAVAS" },
  { banca: "A", n: 39, nombre: "Emilia Sofia Cisterna Brana", club: "FRESIA", categoria: "INFANTIL B ARO" },
  { banca: "B", n: 39, nombre: "Emily Margoth Ramos Mella", club: "AMULEN", categoria: "SENIOR A CLAVAS" },
  { banca: "A", n: 40, nombre: "Emilia Del Rosario Munoz Rivas", club: "ARA", categoria: "INFANTIL B ARO" },
  { banca: "B", n: 40, nombre: "Consuelo Emilia Torres Rivera", club: "AMULEN", categoria: "SENIOR A CLAVAS" },
  { banca: "A", n: 41, nombre: "Emilia Carolina Dobson Varela", club: "KUYEN", categoria: "INFANTIL B ARO" },
  { banca: "B", n: 41, nombre: "Constanza Belen Carrasco Milanca", club: "AMARANTA", categoria: "SENIOR A CLAVAS" },
  { banca: "A", n: 42, nombre: "Elena Carolina Schnettler Bohle", club: "FRESIA", categoria: "INFANTIL B ARO" },
  { banca: "B", n: 42, nombre: "Catalina Fernanda Jaramillo Munoz", club: "ELITE", categoria: "SENIOR A CLAVAS" },
  { banca: "A", n: 43, nombre: "Aneley Julieta Raimilla Fernandez", club: "OLYMPUS", categoria: "INFANTIL B ARO" },
  { banca: "B", n: 43, nombre: "Antonia Becerra Garcia", club: "AMARANTA", categoria: "SENIOR A CLAVAS" },
  { banca: "A", n: 44, nombre: "Ambar Alexa Gonzalez Silva", club: "FRESIA", categoria: "INFANTIL B ARO" },
  { banca: "B", n: 44, nombre: "Antonella Constanza Vegas Godoy", club: "AMULEN", categoria: "SENIOR A CLAVAS" },
  { banca: "A", n: 45, nombre: "Amanda Magdalena Morales Gomez", club: "ELITE", categoria: "INFANTIL B ARO" },
  { banca: "B", n: 45, nombre: "Amaral Andrade", club: "NOVA STELLA", categoria: "SENIOR A CLAVAS" },
  { banca: "A", n: 46, nombre: "Amanda Elisa Hernandez Rupayan", club: "FRESIA", categoria: "INFANTIL B ARO" },

  { banca: "A", n: 1, nombre: "Sofia Valderas Cortes", club: "INTI LOS LAGOS", categoria: "AC2 ELITE ML" },
  { banca: "B", n: 1, nombre: "Amalia Martinez", club: "NOVA STELLA", categoria: "JUNIOR ELITE ARO" },
  { banca: "A", n: 2, nombre: "Emilia Becerra", club: "NOVA STELLA", categoria: "AC2 ELITE ML" },
  { banca: "B", n: 2, nombre: "Ignacia Paz Calfuquir Villegas", club: "AMARANTA", categoria: "JUNIOR ELITE ARO" },
  { banca: "A", n: 3, nombre: "Alessandra Damiani Diaz", club: "INTI LOS LAGOS", categoria: "AC3 ELITE ARO" },
  { banca: "B", n: 3, nombre: "Emilia Carolina Becerra Garcia", club: "AMARANTA", categoria: "JUNIOR ELITE ARO" },
  { banca: "A", n: 4, nombre: "Catalina Victoria Cifuentes Rosa", club: "AMARANTA", categoria: "AC3 ELITE ARO" },
  { banca: "B", n: 4, nombre: "Amanda Rayen Morales Villanueva", club: "ARA", categoria: "AC4 A ARO" },
  { banca: "A", n: 5, nombre: "Emilia De Jesus Abello Arias", club: "AMULEN", categoria: "AC3 ELITE ARO" },
  { banca: "B", n: 5, nombre: "Isabella Saldias", club: "ARA", categoria: "AC4 A ARO" },
  { banca: "A", n: 6, nombre: "Valentina Aravena", club: "NOVA STELLA", categoria: "AC3 ELITE ARO" },
  { banca: "B", n: 6, nombre: "Emilia Bachmann Naulin", club: "ARA", categoria: "AC4 A ARO" },
  { banca: "A", n: 7, nombre: "Valentina Castro", club: "ARA", categoria: "AC4 ELITE ARO" },
  { banca: "B", n: 7, nombre: "Florencia Valentina Garcia Berrocal", club: "AMARANTA", categoria: "AC4 A ARO" },
  { banca: "A", n: 8, nombre: "Paula Hernandez", club: "NOVA STELLA", categoria: "SENIOR ELITE ARO" },
  { banca: "B", n: 8, nombre: "Simone Damiani", club: "INTI LOS LAGOS", categoria: "AC4 A ARO" },
  { banca: "A", n: 9, nombre: "Josefa Gonzalez", club: "NOVA STELLA", categoria: "SENIOR ELITE ARO" },
  { banca: "B", n: 9, nombre: "Amaly Agustina Perez Luna", club: "ELITE", categoria: "JUNIOR B BALON" },
  { banca: "A", n: 10, nombre: "Amalia Martinez", club: "NOVA STELLA", categoria: "JUNIOR ELITE BALON" },
  { banca: "B", n: 10, nombre: "Amelia Gallardo", club: "GR VALDIVIA", categoria: "JUNIOR B BALON" },
  { banca: "A", n: 11, nombre: "Emilia Carolina Becerra Garcia", club: "AMARANTA", categoria: "JUNIOR ELITE BALON" },
  { banca: "B", n: 11, nombre: "Antonia Del Carmen Betancurt Vera", club: "FUTRONO", categoria: "JUNIOR B BALON" },
  { banca: "A", n: 12, nombre: "Ignacia Paz Calfuquir Villegas", club: "AMARANTA", categoria: "JUNIOR ELITE BALON" },
  { banca: "B", n: 12, nombre: "Antonia Espana Gutierrez", club: "TALENTOS", categoria: "JUNIOR B BALON" },
  { banca: "A", n: 13, nombre: "Sofia Valderas Cortes", club: "INTI LOS LAGOS", categoria: "AC2 ELITE CUERDA" },
  { banca: "B", n: 13, nombre: "Constanza Uribe Delgado", club: "TALENTOS", categoria: "JUNIOR B BALON" },
  { banca: "A", n: 14, nombre: "Emilia Becerra", club: "NOVA STELLA", categoria: "AC2 ELITE CUERDA" },
  { banca: "B", n: 14, nombre: "Florencia Hernandez", club: "AMATISTA", categoria: "JUNIOR B BALON" },
  { banca: "A", n: 15, nombre: "Valentina Aravena", club: "NOVA STELLA", categoria: "AC3 ELITE CLAVAS" },
  { banca: "B", n: 15, nombre: "Amanda Diaz", club: "AMATISTA", categoria: "JUNIOR B BALON" },
  { banca: "A", n: 16, nombre: "Emilia De Jesus Abello Arias", club: "AMULEN", categoria: "AC3 ELITE CLAVAS" },
  { banca: "B", n: 16, nombre: "Emilia Isabel Cifuentes Rosa", club: "AMARANTA", categoria: "JUNIOR B BALON" },
  { banca: "A", n: 17, nombre: "Catalina Victoria Cifuentes Rosa", club: "AMARANTA", categoria: "AC3 ELITE CLAVAS" },
  { banca: "B", n: 17, nombre: "Fernanda Revillard San Martin", club: "TALENTOS", categoria: "JUNIOR B BALON" },
  { banca: "A", n: 18, nombre: "Alessandra Damiani Diaz", club: "INTI LOS LAGOS", categoria: "AC3 ELITE CLAVAS" },
  { banca: "B", n: 18, nombre: "Isidora Arias", club: "KUYEN", categoria: "JUNIOR B BALON" },
  { banca: "A", n: 19, nombre: "Carla Gabriela Cuvertino Contreras", club: "ELITE", categoria: "SENIOR ELITE BALON" },
  { banca: "B", n: 19, nombre: "Leonor Antonia Zarges Rivas", club: "OLYMPUS", categoria: "JUNIOR B BALON" },
  { banca: "A", n: 20, nombre: "Josefa Gonzalez", club: "NOVA STELLA", categoria: "SENIOR ELITE BALON" },
  { banca: "B", n: 20, nombre: "Matilda Palma", club: "GR VALDIVIA", categoria: "JUNIOR B BALON" },
  { banca: "A", n: 21, nombre: "Paula Hernandez", club: "NOVA STELLA", categoria: "SENIOR ELITE BALON" },
  { banca: "B", n: 21, nombre: "Omara Figueroa", club: "NOVA STELLA", categoria: "JUNIOR B BALON" },
  { banca: "A", n: 22, nombre: "Amalia Martinez", club: "NOVA STELLA", categoria: "JUNIOR ELITE CLAVAS" },
  { banca: "B", n: 22, nombre: "Renata Candia Uribe", club: "ARA", categoria: "JUNIOR B BALON" },
  { banca: "A", n: 23, nombre: "Emilia Carolina Becerra Garcia", club: "AMARANTA", categoria: "JUNIOR ELITE CLAVAS" },
  { banca: "B", n: 23, nombre: "Amanda Rayen Morales Villanueva", club: "ARA", categoria: "AC4 A CLAVAS" },
  { banca: "A", n: 24, nombre: "Ignacia Paz Calfuquir Villegas", club: "AMARANTA", categoria: "JUNIOR ELITE CLAVAS" },
  { banca: "B", n: 24, nombre: "Emilia Bachmann Naulin", club: "ARA", categoria: "AC4 A CLAVAS" },
  { banca: "A", n: 25, nombre: "Paula Hernandez", club: "NOVA STELLA", categoria: "SENIOR ELITE CLAVAS" },
  { banca: "B", n: 25, nombre: "Isabella Saldias", club: "ARA", categoria: "AC4 A CLAVAS" },
  { banca: "A", n: 26, nombre: "Josefa Gonzalez", club: "NOVA STELLA", categoria: "SENIOR ELITE CLAVAS" },
  { banca: "B", n: 26, nombre: "Alessandra Damiani Diaz", club: "INTI LOS LAGOS", categoria: "AC3 ELITE CINTA" },
  { banca: "A", n: 27, nombre: "Anahi Belen Linay Acuna", club: "ELITE LOS RIOS", categoria: "SENIOR ELITE CLAVAS" },
  { banca: "B", n: 27, nombre: "Catalina Victoria Cifuentes Rosa", club: "AMARANTA", categoria: "AC3 ELITE CINTA" },
  { banca: "A", n: 28, nombre: "Valentina Castro", club: "ARA", categoria: "AC4 ELITE CLAVAS" },
  { banca: "B", n: 28, nombre: "Emilia De Jesus Abello Arias", club: "AMULEN", categoria: "AC3 ELITE CINTA" },
  { banca: "A", n: 29, nombre: "Sofia Valderas Cortes", club: "INTI LOS LAGOS", categoria: "AC2 ELITE ARO" },
  { banca: "B", n: 29, nombre: "Valentina Aravena", club: "NOVA STELLA", categoria: "AC3 ELITE CINTA" },
  { banca: "A", n: 30, nombre: "Emilia Becerra", club: "NOVA STELLA", categoria: "AC2 ELITE ARO" },
  { banca: "B", n: 30, nombre: "Amalia Martinez", club: "NOVA STELLA", categoria: "JUNIOR ELITE CINTA" },
  { banca: "A", n: 31, nombre: "Carla Gabriela Cuvertino Contreras", club: "ELITE", categoria: "SENIOR ELITE CINTA" },
  { banca: "B", n: 31, nombre: "Ignacia Paz Calfuquir Villegas", club: "AMARANTA", categoria: "JUNIOR ELITE CINTA" },
  { banca: "A", n: 32, nombre: "Josefa Gonzalez", club: "NOVA STELLA", categoria: "SENIOR ELITE CINTA" },
  { banca: "B", n: 32, nombre: "Emilia Carolina Becerra Garcia", club: "AMARANTA", categoria: "JUNIOR ELITE CINTA" },
  { banca: "A", n: 33, nombre: "Paula Hernandez", club: "NOVA STELLA", categoria: "SENIOR ELITE CINTA" },

  { banca: "A", n: 1, nombre: "NOVA STELLA", club: "NOVA STELLA", categoria: "DUO OPEN MINI" },
  { banca: "B", n: 1, nombre: "TALENTOS 1", club: "TALENTOS", categoria: "DUO OPEN PREINFANTIL" },
  { banca: "A", n: 2, nombre: "R.ESPANOLA", club: "R.ESPANOLA", categoria: "DUO OPEN PEQUE" },
  { banca: "B", n: 2, nombre: "TALENTOS 2", club: "TALENTOS", categoria: "DUO OPEN PREINFANTIL" },
  { banca: "A", n: 3, nombre: "TALENTOS", club: "TALENTOS", categoria: "TRIO OPEN MINI" },
  { banca: "B", n: 3, nombre: "R.ESPANOLA", club: "R.ESPANOLA", categoria: "DUO OPEN PREINFANTIL" },
  { banca: "A", n: 4, nombre: "R.ESPANOLA", club: "R.ESPANOLA", categoria: "TRIO OPEN MINI" },
  { banca: "B", n: 4, nombre: "CHAYTOR", club: "CHAYTOR", categoria: "DUO OPEN PREINFANTIL" },
  { banca: "A", n: 5, nombre: "PAILLACO", club: "PAILLACO", categoria: "TRIO OPEN MINI" },
  { banca: "B", n: 5, nombre: "ELITE", club: "ELITE", categoria: "DUO OPEN PREINFANTIL" },
  { banca: "A", n: 6, nombre: "ELITE", club: "ELITE", categoria: "TRIO OPEN MINI" },
  { banca: "B", n: 6, nombre: "CAH", club: "CAH", categoria: "DUO OPEN PREINFANTIL" },
  { banca: "A", n: 7, nombre: "GERMANIA", club: "GERMANIA", categoria: "TRIO OPEN MINI" },
  { banca: "B", n: 7, nombre: "ALEMAN TEMUCO", club: "ALEMAN TEMUCO", categoria: "DUO OPEN PREINFANTIL" },
  { banca: "A", n: 8, nombre: "CAH", club: "CAH", categoria: "TRIO OPEN MINI" },
  { banca: "B", n: 8, nombre: "R.ESPANOLA", club: "R.ESPANOLA", categoria: "DUO OPEN INFANTIL" },
  { banca: "A", n: 9, nombre: "AMARANTA", club: "AMARANTA", categoria: "TRIO OPEN MINI" },
  { banca: "B", n: 9, nombre: "AMULEN", club: "AMULEN", categoria: "DUO OPEN INFANTIL" },
  { banca: "A", n: 10, nombre: "R.ESPANOLA", club: "R.ESPANOLA", categoria: "TRIO OPEN PREINFANTIL" },
  { banca: "B", n: 10, nombre: "GERMANIA", club: "GERMANIA", categoria: "DUO OPEN INFANTIL" },
  { banca: "A", n: 11, nombre: "PAILLACO 2", club: "PAILLACO", categoria: "TRIO OPEN PREINFANTIL" },
  { banca: "B", n: 11, nombre: "AMARANTA 1", club: "AMARANTA", categoria: "DUO OPEN INFANTIL" },
  { banca: "A", n: 12, nombre: "PAILLACO 1", club: "PAILLACO", categoria: "TRIO OPEN PREINFANTIL" },
  { banca: "B", n: 12, nombre: "AMARANTA 2", club: "AMARANTA", categoria: "DUO OPEN INFANTIL" },
  { banca: "A", n: 13, nombre: "KUYEN", club: "KUYEN", categoria: "TRIO OPEN PREINFANTIL" },
  { banca: "B", n: 13, nombre: "ALEMAN VILLARRICA", club: "ALEMAN VILLARRICA", categoria: "DUO OPEN INFANTIL" },
  { banca: "A", n: 14, nombre: "KUYEN", club: "KUYEN", categoria: "TRIO OPEN INFANTIL" },
  { banca: "B", n: 14, nombre: "TALENTOS", club: "TALENTOS", categoria: "DUO OPEN JUNIOR" },
  { banca: "A", n: 15, nombre: "GR RIO BUENO", club: "GR RIO BUENO", categoria: "CONJUNTO OPEN MINI" },
  { banca: "B", n: 15, nombre: "AMULEN", club: "AMULEN", categoria: "DUO OPEN SENIOR" },
  { banca: "A", n: 16, nombre: "AMARANTA", club: "AMARANTA", categoria: "CONJUNTO OPEN MINI" },
  { banca: "B", n: 16, nombre: "KUYEN", club: "KUYEN", categoria: "TRIO OPEN SENIOR" },
  { banca: "A", n: 17, nombre: "ALEMAN TEMUCO", club: "ALEMAN TEMUCO", categoria: "CONJUNTO OPEN MINI" },
  { banca: "B", n: 17, nombre: "GR VALDIVIA", club: "GR VALDIVIA", categoria: "TRIO OPEN SENIOR" },
  { banca: "A", n: 18, nombre: "ORIGENES", club: "ORIGENES", categoria: "CONJUNTO OPEN INFANTIL" },
  { banca: "B", n: 18, nombre: "GR RIO BUENO", club: "GR RIO BUENO", categoria: "CONJUNTO OPEN PREINFANTIL" },
  { banca: "A", n: 19, nombre: "KUYEN", club: "KUYEN", categoria: "CONJUNTO OPEN INFANTIL" },
  { banca: "B", n: 19, nombre: "AMULEN", club: "AMULEN", categoria: "CONJUNTO OPEN PREINFANTIL" },
  { banca: "A", n: 20, nombre: "GR RIO BUENO", club: "GR RIO BUENO", categoria: "CONJUNTO OPEN INFANTIL" },
  { banca: "B", n: 20, nombre: "ALEMAN VILLARRICA", club: "ALEMAN VILLARRICA", categoria: "CONJUNTO OPEN PREINFANTIL" },
  { banca: "A", n: 21, nombre: "CAH", club: "CAH", categoria: "CONJUNTO OPEN INFANTIL" },
  { banca: "B", n: 21, nombre: "CAH", club: "CAH", categoria: "CONJUNTO OPEN JUNIOR" },
  { banca: "A", n: 22, nombre: "ALEMAN TEMUCO", club: "ALEMAN TEMUCO", categoria: "CONJUNTO OPEN INFANTIL" },
  { banca: "B", n: 22, nombre: "AMULEN", club: "AMULEN", categoria: "CONJUNTO OPEN SENIOR" },
  { banca: "A", n: 23, nombre: "ORIGENES", club: "ORIGENES", categoria: "TRIO AC2 ELITE" },
  { banca: "B", n: 23, nombre: "NOVA STELLA", club: "NOVA STELLA", categoria: "TRIO SENIOR ELITE" }
];
