export const sabado = [
  { banca: "A", n: 1, nombre: "Agustina Ignacia Garrido Miranda", club: "HUELLAS", categoria: "MINI F ML" },
  { banca: "B", n: 1, nombre: "Victoria Wilde Garrido", club: "CISNES", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 2, nombre: "Agustina Pia Schafer Banados", club: "PAILLACO", categoria: "MINI F ML" },
  { banca: "B", n: 2, nombre: "Valentina Rebolledo", club: "ALMA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 3, nombre: "Alba Simone Vives Hidalgo", club: "PAILLACO", categoria: "MINI F ML" },
  { banca: "B", n: 3, nombre: "Valentina Isabella Carrillo Henriquez", club: "AMARANTA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 4, nombre: "Alondra Valentina Acevedo Gatica", club: "FUTRONO", categoria: "MINI F ML" },
  { banca: "B", n: 4, nombre: "Stephanie Nicole Monroy Maldonado", club: "AMULEN", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 5, nombre: "Amanda Aguilera", club: "GREENHOUSE", categoria: "MINI F ML" },
  { banca: "B", n: 5, nombre: "Sophia Vollmer Tenorio", club: "TALENTOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 6, nombre: "Amanda Ysabel Godoy Briceno", club: "ELITE", categoria: "MINI F ML" },
  { banca: "B", n: 6, nombre: "Sophia Gomez Mellado", club: "TALENTOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 7, nombre: "Amira Leticia Velazco Acosta", club: "ORIGENES", categoria: "MINI F ML" },
  { banca: "B", n: 7, nombre: "Sofia Nercelles", club: "PAILLACO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 8, nombre: "Antonella Giacomozzi Vera", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 8, nombre: "Sofia Munoz Toledo", club: "CAH", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 9, nombre: "Antonia Fonseca Vera", club: "CHAYTOR", categoria: "MINI F ML" },
  { banca: "B", n: 9, nombre: "Sofia Antonella Gonzalez Perez", club: "PAILLACO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 10, nombre: "Arantza Yuliet Yumar Lobo", club: "ELITE", categoria: "MINI F ML" },
  { banca: "B", n: 10, nombre: "Renata Isidora Cobos Ili", club: "PAILLACO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 11, nombre: "Barbara Zuniga Mancilla", club: "TRAVESIA", categoria: "MINI F ML" },
  { banca: "B", n: 11, nombre: "Pia Torres Zamorano", club: "CHAYTOR", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 12, nombre: "Begona Arrigorriaga Pinto", club: "CHAYTOR", categoria: "MINI F ML" },
  { banca: "B", n: 12, nombre: "Monserrat Contreras Tejos", club: "GR LAUTARO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 13, nombre: "Carlota Daniella Gutierrez Camargo", club: "ELITE", categoria: "MINI F ML" },
  { banca: "B", n: 13, nombre: "Matilde De Jourdan Carrillo", club: "ALEMAN VILLARRICA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 14, nombre: "Colomba Thomas Leiva", club: "FRESIA", categoria: "MINI F ML" },
  { banca: "B", n: 14, nombre: "Matilda Nett Navarrete", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 15, nombre: "Ema Alejandra Quiyinao Barrientos", club: "ORIGENES", categoria: "MINI F ML" },
  { banca: "B", n: 15, nombre: "Matilda Dumenes Rojas", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 16, nombre: "Emilia Antonela Carcamo Quezada", club: "PAILLACO", categoria: "MINI F ML" },
  { banca: "B", n: 16, nombre: "Martina Miralles", club: "GR VALDIVIA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 17, nombre: "Emilia Navarrete Tillemann", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 17, nombre: "Maithe Aguilar Rodriguez", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 18, nombre: "Emma Catalina Baeza Aguilera", club: "ORIGENES", categoria: "MINI F ML" },
  { banca: "B", n: 18, nombre: "Maite Nunez Fernandez", club: "INTI LOS LAGOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 19, nombre: "Emma Victoria Luengo Chacon", club: "R.ESPANOLA", categoria: "MINI F ML" },
  { banca: "B", n: 19, nombre: "Magdalena Calisto Cisterna", club: "TRAVESIA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 20, nombre: "Florencia Isidora Millar Navarrete", club: "AMULEN", categoria: "MINI F ML" },
  { banca: "B", n: 20, nombre: "Laura Paz Hernandez Saez", club: "HUELLAS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 21, nombre: "Gretta Gonzalez Pineda", club: "PAILLACO", categoria: "MINI F ML" },
  { banca: "B", n: 21, nombre: "Laura Duran Werth", club: "ALEMAN VILLARRICA", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 22, nombre: "Helena Yanez Munoz", club: "INTI LOS LAGOS", categoria: "MINI F ML" },
  { banca: "B", n: 22, nombre: "Josefina Vasquez Sayeg", club: "TALENTOS", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 23, nombre: "Ignacia Araya", club: "GR VALDIVIA", categoria: "MINI F ML" },
  { banca: "B", n: 23, nombre: "Josefina Pauline Schafer Banados", club: "PAILLACO", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 24, nombre: "Ignacia Barrientos Rubio", club: "FRESIA", categoria: "MINI F ML" },
  { banca: "B", n: 24, nombre: "Josefa Verdello", club: "GREENHOUSE", categoria: "PREINFANTIL F ML" },
  { banca: "A", n: 25, nombre: "Ignacia Pedrero Herrera", club: "TALENTOS", categoria: "MINI F ML" },
  { banca: "B", n: 25, nombre: "Josefa Admore Jaduri Cardenas", club: "PAILLACO", categoria: "PREINFANTIL F ML" }
];

export const domingo = [
  { banca: "A", n: 1, nombre: "Agustina Ormazabal", club: "CAH", categoria: "INFANTIL F ML" },
  { banca: "B", n: 1, nombre: "Agustina Chavez Henriquez", club: "OHIGGINS", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 2, nombre: "Agustina Vargas Vara", club: "ALMA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 2, nombre: "Alfonsina Higuera Aburto", club: "ORIGENES", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 3, nombre: "Amelie Schadt Brunner", club: "ALEMAN VILLARRICA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 3, nombre: "Alonsa Ignacia Sandoval Salas", club: "ELITE", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 4, nombre: "Blanca Reinike Duran", club: "ALEMAN VILLARRICA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 4, nombre: "Antonia Florencia Ruiz Bravo", club: "AMARANTA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 5, nombre: "Emilia Antonia Azua Letelier", club: "ARA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 5, nombre: "Antonia Sepulveda", club: "CAH", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 6, nombre: "Emilia Diaz Miranda", club: "TRAVESIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 6, nombre: "Fernanda Javiera Dominguez Manquel", club: "OLYMPUS", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 7, nombre: "Emilia Mora Gaete", club: "TALENTOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 7, nombre: "Javiera Anais Valencia Vallejo", club: "AMARANTA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 8, nombre: "Emily Garate", club: "GR VALDIVIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 8, nombre: "Josefina Ignacia Morales Valenzuela", club: "AMARANTA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 9, nombre: "Emma Schneider Trejo", club: "ALEMAN TEMUCO", categoria: "INFANTIL F ML" },
  { banca: "B", n: 9, nombre: "Laura Barckhahn", club: "NOVA STELLA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 10, nombre: "Emma Yurjevic Moreno", club: "ALEMAN VILLARRICA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 10, nombre: "Llampuzken Raimil", club: "KUYEN", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 11, nombre: "Evelyn Opitz Miranda", club: "TALENTOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 11, nombre: "Maria Jesus Medina Bustamante", club: "KUYEN", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 12, nombre: "Florencia Isidora Inostroza Silva", club: "FUTRONO", categoria: "INFANTIL F ML" },
  { banca: "B", n: 12, nombre: "Martina Gabriela Rivera Velasquez", club: "FUTRONO", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 13, nombre: "Ignacia Pinto", club: "GR VALDIVIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 13, nombre: "Matilda Alvarado Ruiz", club: "OHIGGINS", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 14, nombre: "Isabella Higuera", club: "GR VALDIVIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 14, nombre: "Noemi Gonzalez Kahler", club: "INTI LOS LAGOS", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 15, nombre: "Javiera Morales Mulato", club: "CHAYTOR", categoria: "INFANTIL F ML" },
  { banca: "B", n: 15, nombre: "Rosario Romero", club: "CAH", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 16, nombre: "Josefa Contreras", club: "GR VALDIVIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 16, nombre: "Sofia Cardenas", club: "NOVA STELLA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 17, nombre: "Josefa Wachter Schrag", club: "AMARANTA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 17, nombre: "Sofia Ignacia Andrades Munoz", club: "R.ESPANOLA", categoria: "PREINFANTIL B ML" },
  { banca: "A", n: 18, nombre: "Julieta Sofia Cabezas Alday", club: "ORIGENES", categoria: "INFANTIL F ML" },
  { banca: "B", n: 18, nombre: "Amaral Andrade", club: "NOVA STELLA", categoria: "SENIOR A BALON" },
  { banca: "A", n: 19, nombre: "Laura Hornig Fischer", club: "INTI LOS LAGOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 19, nombre: "Antonia Becerra Garcia", club: "AMARANTA", categoria: "SENIOR A BALON" },
  { banca: "A", n: 20, nombre: "Mailen Asenjo Cardenas", club: "INTI LOS LAGOS", categoria: "INFANTIL F ML" },
  { banca: "B", n: 20, nombre: "Constanza Belen Carrasco Milanca", club: "AMARANTA", categoria: "SENIOR A BALON" },
  { banca: "A", n: 21, nombre: "Maite Lara", club: "GERMANIA", categoria: "INFANTIL F ML" },
  { banca: "B", n: 21, nombre: "Antonella Constanza Vegas Godoy", club: "AMULEN", categoria: "SENIOR A BALON" },
  { banca: "A", n: 22, nombre: "Millaray Angelita Aravena Hernandez", club: "PAILLACO", categoria: "INFANTIL F ML" },
  { banca: "B", n: 22, nombre: "Consuelo Emilia Torres Rivera", club: "AMULEN", categoria: "SENIOR A BALON" },
  { banca: "A", n: 23, nombre: "Montserrat Anahi Arias Zevallos", club: "PAILLACO", categoria: "INFANTIL F ML" },
  { banca: "B", n: 23, nombre: "Emily Margoth Ramos Mella", club: "AMULEN", categoria: "SENIOR A BALON" },
  { banca: "A", n: 24, nombre: "Olivia Gallardo Collinao", club: "CHAYTOR", categoria: "INFANTIL F ML" },
  { banca: "B", n: 24, nombre: "Josefa Valentina Figueroa Aguilera", club: "AMULEN", categoria: "SENIOR A BALON" },
  { banca: "A", n: 25, nombre: "Pascale", club: "KUYEN", categoria: "INFANTIL F ML" },
  { banca: "B", n: 25, nombre: "Sofia Isidora Fonseca Avila", club: "AMULEN", categoria: "SENIOR A BALON" }
];
